services:
  mysql:
    image: mysql:8.3.0
    container_name: borrow-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql


