services:
  mysql:
    image: mysql:8.3.0
    container_name: books-service
    ports:
      - "3316:3316"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
