package com.hamami.bookservice.model;

public enum Genre {
    FICTION, NONFICTION, CLASSIC, MYSTERY, THRILLER, HORROR, SCIENCE_FICTION, FANTASY, ROMANCE, WESTERN, DYSTOPIAN, ADVENTURE, HISTORICAL, BIOGRAPHY, SELF_HELP, HEALTH, TRAVEL, CHILDREN, RELIGION, SCIENCE, COOKBOOK, POETRY, ART, PERSONAL_DEVELOPMENT, BUSINESS, EDUCATIONAL, POLITICS, LAW, MUSIC, THEATER, NOVEL, OTHER;

}



